
---
- hosts: localhost
  become: yes
  gather_facts: false

  vars:
    aws_access_key: Access_keys
    aws_secret_key: Secret_keys
    title: "ARTH"
    vpc_name: Sushree2_vpc
    igw_name: Sushree2_igw
    pubsubnet_name: Sushree2_pub
    pvtsubnet_name: Sushree2_pvt
    pubroute_table_name: Sushree2_pub_rt
    pvtroute_table_name: Sushree2_pvt_rt
    security_group_name: Sushree2-sg
    vpc_cidr_block: '11.0.0.0/16'
    pubsubnet_cidr_block: '11.0.1.0/24'
    pvtsubnet_cidr_block: '11.0.2.0/24'
    destination_cidr_block: '0.0.0.0/0'
    port22_cidr_block: '0.0.0.0/0'
    region: "us-east-2"
    pubzone: "us-east-2a"
    pvtzone: "us-east-2b"
    image_id: "ami-00cda30cf72311684"
    type: "t2.micro"
    instance_name: Sushree2_EC2
    alb_name: Sushree2-alb
    asg_name: Sushree2-asg
    launch_config_name: Sushree2-LC

  tasks:
    - name: VPC creation
      ec2_vpc_net:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        cidr_block: "{{ vpc_cidr_block }}"
        name: "{{ vpc_name }}"
        region: "{{ region }}"
        tenancy: default
        state: present
      register: vpc_result

    - name: IGW creation
      ec2_vpc_igw:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ igw_name }}"
      register: igw_result

    - name: VPC public Subnet creation
      ec2_vpc_subnet:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        az: "{{ pubzone }}"
        state: present
        cidr: "{{ pubsubnet_cidr_block }}"
        map_public: yes
        resource_tags:
          Name: "{{ pubsubnet_name }}"
      register: pubsubnet_result

    - name: VPC private Subnet creation
      ec2_vpc_subnet:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        az: "{{ pvtzone }}"
        state: present
        cidr: "{{ pvtsubnet_cidr_block }}"
        map_public: no
        resource_tags:
          Name: "{{ pvtsubnet_name }}"
      register: pvtsubnet_result

    - name: public Route Table creation
      ec2_vpc_route_table:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ pubroute_table_name }}"
        subnets: [ "{{ pubsubnet_result.subnet.id }}" ]
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id }}"
      register: public_route_table

    - name: private Route Table creation
      ec2_vpc_route_table:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ pvtroute_table_name }}"
        subnets: [ "{{ pvtsubnet_result.subnet.id }}" ]
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id }}"
      register: private_route_table

    - name: Security Groups creation
      ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        name: "{{ security_group_name }}"
        description: allow
        tags:
          Name: Sushree2_sg
        rules:
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic
      register: security_group_results

    - ec2_elb_lb:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ alb_name }}"
        state: present
        region: "{{ region }}"
        security_group_ids: ["{{ security_group_results.group_id }}"]
        subnets: ["{{ pubsubnet_result.subnet.id }}"]
        listeners:
          - protocol: HTTP
            load_balancer_port: 80
            instance_port: 80

    - name: Create Launch Configuration
      ec2_lc:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ launch_config_name }}"
        image_id: "{{ image_id }}"
        security_groups: ["{{ security_group_name }}"]
        instance_type: "{{ type }}"
        key_name: "ohio"
        region: "{{ region }}"
      register: launch_config

    - ec2_asg:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ asg_name }}"
        launch_config_name: "{{ launch_config_name }}"
        min_size: 2
        max_size: 4
        desired_capacity: 2
        region: "{{ region }}"
        vpc_zone_identifier:
         - "{{ pubsubnet_result.subnet.id }}"
        tags:
          - key: "Name"
            value: "{{ asg_name }}"
            propagate_at_launch: true

    - name: Launch EC2 instance creation
      ec2:
        image: "{{ image_id }}"
        instance_type: "{{ type }}"
        region: "{{ region }}"
        wait: yes
        count: 1
        state: present
        vpc_subnet_id: "{{ pubsubnet_result.subnet.id }}"
        assign_public_ip: yes
        group_id: "{{ security_group_results.group_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "ohio"
        instance_tags:
          Name: "{{ instance_name }}"
        user_data: |
          #!/bin/bash
          sudo yum install git httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          git clone https://github.com/sweety-shree/ecomm.git /var/www/html/

