
---
- hosts: localhost
  become: yes
  gather_facts: false
  vars_files:
    - secret.yml

  tasks:

#VPC creation
    - name: Create VPC
      ec2_vpc_net:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        cidr_block: "{{ vpc_cidr_block }}"
        name: "{{ vpc_name }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: present
      register: vpc_result


#IGW creation
    - name: Create Internet Gateway
      ec2_vpc_igw:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ igw_name }}"
      register: igw_result

#Public-subnet creation
    - name: Create VPC Public Subnet
      ec2_vpc_subnet:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        az: "{{ pubzone }}"
        state: present
        cidr: "{{ pubsubnet_cidr_block }}"
        map_public: yes
        resource_tags:
          Name: "{{ pubsubnet_name }}"
      register: pubsubnet_result

#Private-subnet creation
    - name: Create VPC Private Subnet
      ec2_vpc_subnet:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        az: "{{ pvtzone }}"
        state: present
        cidr: "{{ pvtsubnet_cidr_block }}"
        map_public: no
        resource_tags:
          Name: "{{ pvtsubnet_name }}"
      register: pvtsubnet_result

#public-Route table
    - name: Create VPC Public Route Table
      ec2_vpc_route_table:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ pubroute_table_name }}"
        subnets:
          - "{{ pubsubnet_result.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id }}"
      register: public_route_table

#Private-Route table
    - name: Create VPC Private Route Table
      ec2_vpc_route_table:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ pvtroute_table_name }}"
        subnets:
          - "{{ pvtsubnet_result.subnet.id }}"
      register: private_route_table

#Security-group
    - name: Create VPC Security Group
      ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ region }}"
        state: present
        name: "{{ security_group_name }}"
        description: allow
        tags:
          Name: Sushree3-sg
        rules:
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic
      register: security_group_results

#EC2 Instance
    - name: Launch EC2 Instance
      ec2:
        image: "{{ image_id }}"
        instance_type: "{{ type }}"
        region: "{{ region }}"
        wait: yes
        count: 1
        state: present
        vpc_subnet_id: "{{ pubsubnet_result.subnet.id }}"
        assign_public_ip: yes
        group_id: "{{ security_group_results.group_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_tags:
          Name: "{{ instance_name }}"
        user_data: |
          #!/bin/bash
          sudo yum -y install git httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          git clone https://github.com/sweety-shree/Mario.git /var/www/html/

##ELB creation
    - name: Create ELB
      ec2_elb_lb:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: Sushree3-elb
        region: "{{ region }}"
        state: present
        subnets:
          - "{{ pubsubnet_result.subnet.id }}"
        security_group_ids:
          - "{{ security_group_results.group_id }}"
        listeners:
          - protocol: HTTP
            load_balancer_port: 80
            instance_protocol: HTTP
            instance_port: 80
        tags:
          Name: Sushree3-elb

#Launch configuration
    - name: Create Launch Configuration
      ec2_lc:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ launch_config_name }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ type }}"
        region: "{{ region }}"
        key_name: "ohio"
        security_groups: ["{{ security_group_name }}"]
        instance_monitoring: yes
      register: launch_config

#ASG creation
    - name: Create Auto Scaling Group
      ec2_asg:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        name: Sushree3-asg
        launch_config_name: "{{ launch_config_name }}"
        min_size: 2
        max_size: 4
        desired_capacity: 2
        vpc_zone_identifier:
          - "{{ pubsubnet_result.subnet.id }}"
        load_balancers: ["{{ elb_name }}"]
        tags:
          - key: ohio
            value: "{{ asg_name }}"
            propagate_at_launch: true


